# 13. Machine learning techniques

### Importing Packages

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
import random as rd
rd.seed(0)

## 13.1 Loading and exploring the dataset

For the next two cells, please run only one of them.
- Run the first cell if you cloned the Github Repo
- Run the second cell if you opened this as a Google Colab

In [6]:
# IMPORTANT: ONLY RUN THIS CELL IF YOU HAVE CLONED THE REPO
raw_data = pd.read_csv('./titanic.csv')
raw_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# IMPORTANT: ONLY RUN THIS CELL IF YOU ARE WORKING ON A COLAB

url = "https://raw.githubusercontent.com/luisguiserrano/manning/master/Chapter_13_End_to_end_example/titanic.csv"
raw_data = pd.read_csv(url)
raw_data.head()

Next, we can explore the dataset.

In [7]:
# Examining the length of the dataset
print("The dataset has", len(raw_data), "rows")

The dataset has 891 rows

In [8]:
# Examining the columns in the dataset
print("Columns (features of the dataset)")
raw_data.columns

Columns (features of the dataset)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [9]:
# Examining the labels
print("Labels")
raw_data["Survived"]

Labels

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [10]:
# Examining how many passengers survived
print(sum(raw_data['Survived']),'passengers survived out of',len(raw_data))

342 passengers survived out of 891

In [11]:
# One can look at several columns together
raw_data[["Name", "Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

## 13.2. Cleaning up the data

Now, let's look at how many columns have missing data

In [12]:
raw_data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

The Cabin column is missing too many values to be useful. Let's drop it altogether.

In [13]:
raw_data['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: str

In [14]:
print("The Cabin column is missing", sum(raw_data['Cabin'].isna()), "values out of",len(raw_data['Cabin']))

The Cabin column is missing 687 values out of 891

In [15]:
preprocessed_data = raw_data.drop('Cabin', axis=1)

In [16]:
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

Other columns such as Age or Embarked are missing some values, but they can still be useful.

For the age column, let's fill in the missing values with the median of all ages.

For the Embarked column, let's make a new category called 'U', for Unknown port of embarkment.

In [17]:
preprocessed_data['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [18]:
median_age = raw_data["Age"].median()
median_age

np.float64(28.0)

In [19]:
preprocessed_data["Age"] = preprocessed_data["Age"].fillna(median_age)

In [20]:
preprocessed_data["Embarked"] = preprocessed_data["Embarked"].fillna('U')

In [21]:
preprocessed_data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [22]:
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

## 12.3 Manipulating the features

- One-hot encoding
- Binning
- Feature selection

### 13.3.1 One-hot encoding

One-hot encoding the gender feature

In [24]:
gender_columns = pd.get_dummies(preprocessed_data['Sex'], prefix='Sex')
print(gender_columns)
embarked_columns = pd.get_dummies(preprocessed_data["Embarked"], prefix="Embarked")
print(embarked_columns)

     Sex_female  Sex_male
0         False      True
1          True     False
2          True     False
3          True     False
4         False      True
..          ...       ...
886       False      True
887        True     False
888        True     False
889       False      True
890       False      True

[891 rows x 2 columns]
     Embarked_C  Embarked_Q  Embarked_S  Embarked_U
0         False       False        True       False
1          True       False       False       False
2         False       False        True       False
3         False       False        True       False
4         False       False        True       False
..          ...         ...         ...         ...
886       False       False        True       False
887       False       False        True       False
888       False       False        True       False
889        True       False       False       False
890       False        True       False       False

[891 rows x 4 columns]

In [25]:
preprocessed_data = pd.concat([preprocessed_data, gender_columns], axis=1)
preprocessed_data = pd.concat([preprocessed_data, embarked_columns], axis=1)

In [26]:
preprocessed_data = preprocessed_data.drop(['Sex', 'Embarked'], axis=1)

In [27]:
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,False,True,False,False,True,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,True,False,True,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,True,False,False,False,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,True,False,False,False,True,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,False,True,False,False,True,False

### A rule of thumb for when to one-hot encode or not

In [28]:
class_survived = preprocessed_data[['Pclass', 'Survived']]

first_class = class_survived[class_survived['Pclass'] == 1]
second_class = class_survived[class_survived['Pclass'] == 2]
third_class = class_survived[class_survived['Pclass'] == 3]

print("In first class", sum(first_class['Survived'])/len(first_class)*100, "% of passengers survived")
print("In second class", sum(second_class['Survived'])/len(second_class)*100, "% of passengers survived")
print("In third class", sum(third_class['Survived'])/len(third_class)*100, "% of passengers survived")

In first class 62.96296296296296 % of passengers survived
In second class 47.28260869565217 % of passengers survived
In third class 24.236252545824847 % of passengers survived

In [30]:
categorized_pclass_columns = pd.get_dummies(preprocessed_data['Pclass'], prefix='Pclass')
preprocessed_data = pd.concat([preprocessed_data, categorized_pclass_columns], axis=1)
preprocessed_data = preprocessed_data.drop(['Pclass'], axis=1)

In [31]:
preprocessed_data.head()

,PassengerId,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,Pclass_1,Pclass_2,Pclass_3
0,1,0,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,False,True,False,False,True,False,False,False,True
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,True,False,True,False,False,False,True,False,False
2,3,1,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,True,False,False,False,True,False,False,False,True
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,True,False,False,False,True,False,True,False,False
4,5,0,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,False,True,False,False,True,False,False,False,True

### 13.3.3 Binning

In [32]:
bins = [0, 10, 20, 30, 40, 50, 60, 70, 80]
categorized_age = pd.cut(preprocessed_data['Age'], bins)
preprocessed_data['Categorized_age'] = categorized_age
preprocessed_data = preprocessed_data.drop(["Age"], axis=1)

In [33]:
preprocessed_data.head()

,PassengerId,Survived,Name,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,Pclass_1,Pclass_2,Pclass_3,Categorized_age
0,1,0,"Braund, Mr. Owen Harris",1,0,A/5 21171,7.2500,False,True,False,False,True,False,False,False,True,"(20, 30]"
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,PC 17599,71.2833,True,False,True,False,False,False,True,False,False,"(30, 40]"
2,3,1,"Heikkinen, Miss. Laina",0,0,STON/O2. 3101282,7.9250,True,False,False,False,True,False,False,False,True,"(20, 30]"
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,113803,53.1000,True,False,False,False,True,False,True,False,False,"(30, 40]"
4,5,0,"Allen, Mr. William Henry",0,0,373450,8.0500,False,True,False,False,True,False,False,False,True,"(30, 40]"

In [36]:
cagegorized_age_columns = pd.get_dummies(preprocessed_data['Categorized_age'], prefix='Categorized_age')
preprocessed_data = pd.concat([preprocessed_data, cagegorized_age_columns], axis=1)
preprocessed_data = preprocessed_data.drop(['Categorized_age'], axis=1)

In [41]:
preprocessed_data.head()

,Survived,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,...,Pclass_2,Pclass_3,"Categorized_age_(0, 10]","Categorized_age_(10, 20]","Categorized_age_(20, 30]","Categorized_age_(30, 40]","Categorized_age_(40, 50]","Categorized_age_(50, 60]","Categorized_age_(60, 70]","Categorized_age_(70, 80]"
0,0,1,0,7.2500,False,True,False,False,True,False,...,False,True,False,False,True,False,False,False,False,False
1,1,1,0,71.2833,True,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,1,0,0,7.9250,True,False,False,False,True,False,...,False,True,False,False,True,False,False,False,False,False
3,1,1,0,53.1000,True,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
4,0,0,0,8.0500,False,True,False,False,True,False,...,False,True,False,False,False,True,False,False,False,False

### 13.3.3 Feature selection

In [42]:
preprocessed_data = preprocessed_data.drop(['Name', 'Ticket', 'PassengerId'], axis=1)

KeyError: "['Name', 'Ticket', 'PassengerId'] not found in axis"

In [43]:
preprocessed_data.head()

,Survived,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,...,Pclass_2,Pclass_3,"Categorized_age_(0, 10]","Categorized_age_(10, 20]","Categorized_age_(20, 30]","Categorized_age_(30, 40]","Categorized_age_(40, 50]","Categorized_age_(50, 60]","Categorized_age_(60, 70]","Categorized_age_(70, 80]"
0,0,1,0,7.2500,False,True,False,False,True,False,...,False,True,False,False,True,False,False,False,False,False
1,1,1,0,71.2833,True,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,1,0,0,7.9250,True,False,False,False,True,False,...,False,True,False,False,True,False,False,False,False,False
3,1,1,0,53.1000,True,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
4,0,0,0,8.0500,False,True,False,False,True,False,...,False,True,False,False,False,True,False,False,False,False

# 13.4 Training models

### 13.4.1 Features-labels split and train-validation split

In [44]:
data = preprocessed_data

In [45]:
features = data.drop(["Survived"], axis=1)
labels = data["Survived"]

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
# remark: we fix random_state the end, to make sure we always get the same split
features_train, features_validation_test, labels_train, labels_validation_test = train_test_split(
    features, labels, test_size=0.4, random_state=100)

In [48]:
features_validation, features_test, labels_validation, labels_test = train_test_split(
    features_validation_test, labels_validation_test, test_size=0.5, random_state=100)

In [49]:
print(len(features_train))
print(len(features_validation))
print(len(features_test))
print(len(labels_train))
print(len(labels_validation))
print(len(labels_test))

534
178
179
534
178
179

### 13.4.2 Training different models on our dataset

We'll train four models:
- Logistic regression (perceptron)
- Decision tree
- Naive Bayes
- Support vector machine (SVM)

In [50]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
lr_model.fit(features_train, labels_train)

/data/data/com.termux/files/usr/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [51]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()
dt_model.fit(features_train, labels_train)

DecisionTreeClassifier()

In [52]:
from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model.fit(features_train, labels_train)

GaussianNB()

In [53]:
from sklearn.svm import SVC

svm_model = SVC()
svm_model.fit(features_train, labels_train)

SVC()

In [54]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()
rf_model.fit(features_train, labels_train)

RandomForestClassifier()

In [55]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier()
gb_model.fit(features_train, labels_train)

GradientBoostingClassifier()

In [56]:
from sklearn.ensemble import AdaBoostClassifier

ab_model = AdaBoostClassifier()
ab_model.fit(features_train, labels_train)

AdaBoostClassifier()

### 13.4.3 Evaluating the models

#### Accuracy

In [57]:
print("Scores of the models")
print("Logistic regression:", lr_model.score(features_validation, labels_validation))
print("Decision tree:", dt_model.score(features_validation, labels_validation))
print("Naive Bayes:", nb_model.score(features_validation, labels_validation))
print("SVM:", svm_model.score(features_validation, labels_validation))
print("Random forest:", rf_model.score(features_validation, labels_validation))
print("Gradient boosting:", gb_model.score(features_validation, labels_validation))
print("AdaBoost:", ab_model.score(features_validation, labels_validation))

Scores of the models
Logistic regression: 0.7696629213483146
Decision tree: 0.7808988764044944
Naive Bayes: 0.7471910112359551
SVM: 0.6797752808988764
Random forest: 0.7865168539325843
Gradient boosting: 0.8089887640449438
AdaBoost: 0.7359550561797753

#### F1-score

In [60]:
from sklearn.metrics import f1_score

print("F1-scores of the models:")

lr_predicted_labels = lr_model.predict(features_validation)
print("Logistic regression:", f1_score(labels_validation, lr_predicted_labels))

dt_predicted_labels = dt_model.predict(features_validation)
print("Decision Tree:", f1_score(labels_validation, dt_predicted_labels))

nb_predicted_labels = nb_model.predict(features_validation)
print("Naive Bayes:", f1_score(labels_validation, nb_predicted_labels))

svm_predicted_labels = svm_model.predict(features_validation)
print("Support Vector Machine:", f1_score(labels_validation, svm_predicted_labels))

rf_predicted_labels = rf_model.predict(features_validation)
print("Random Forest:", f1_score(labels_validation, rf_predicted_labels))

gb_predicted_labels = gb_model.predict(features_validation)
print("Gradient boosting:", f1_score(labels_validation, gb_predicted_labels))

ab_predicted_labels = ab_model.predict(features_validation)
print("AdaBoost:", f1_score(labels_validation, ab_predicted_labels))

F1-scores of the models:
Logistic regression: 0.6870229007633588
Decision Tree: 0.7111111111111111
Naive Bayes: 0.6808510638297872
Support Vector Machine: 0.4
Random Forest: 0.7205882352941176
Gradient boosting: 0.7384615384615385
AdaBoost: 0.6466165413533834

### 13.4.4 Testing the model

Finding the accuracy and the F1-score of the model in the testing set.

In [61]:
gb_model.score(features_test, labels_test)

0.8324022346368715

In [62]:
gb_predicted_test_labels = gb_model.predict(features_test)
f1_score(labels_test, gb_predicted_test_labels)

0.8026315789473685

# 13.5 Grid search

In [63]:
from sklearn.model_selection import GridSearchCV

In [65]:
# Grid search with an rbf kernel

print("SVM grid search with a radial basis function kernel")

# rbf, C=1, gamma=0.1
svm_1_01 = SVC(kernel='rbf', C=1, gamma=0.1)
svm_1_01.fit(features_train, labels_train)
print("C=1, gamma=0.1", svm_1_01.score(features_validation, labels_validation))

# rbf, C=1, gamma=1
svm_1_1 = SVC(kernel='rbf', C=1, gamma=1)
svm_1_1.fit(features_train, labels_train)
print("C=1, gamma=1", svm_1_1.score(features_validation, labels_validation))

# rbf, C=1, gamma=10
svm_1_10 = SVC(kernel='rbf', C=1, gamma=10)
svm_1_10.fit(features_train, labels_train)
print("C=1, gamma=10", svm_1_10.score(features_validation, labels_validation))

# rbf, C=10, gamma=0.1
svm_10_01 = SVC(kernel='rbf', C=10, gamma=0.1)
svm_10_01.fit(features_train, labels_train)
print("C=10, gamma=0.1", svm_10_01.score(features_validation, labels_validation))

# rbf, C=10, gamma=1
svm_10_1 = SVC(kernel='rbf', C=10, gamma=1)
svm_10_1.fit(features_train, labels_train)
print("C=10, gamma=1", svm_10_1.score(features_validation, labels_validation))

# rbf, C=10, gamma=10
svm_10_10 = SVC(kernel='rbf', C=10, gamma=10)
svm_10_10.fit(features_train, labels_train)
print("C=10, gamma=10", svm_10_10.score(features_validation, labels_validation))

SVM grid search with a radial basis function kernel
C=1, gamma=0.1 0.702247191011236
C=1, gamma=1 0.6966292134831461
C=1, gamma=10 0.6685393258426966
C=10, gamma=0.1 0.7247191011235955
C=10, gamma=1 0.6910112359550562
C=10, gamma=10 0.651685393258427

In [66]:
svm_parameters = {'kernel': ['rbf'],
                  'C': [0.01, 0.1, 1 , 10, 100],
                  'gamma': [0.01, 0.1, 1, 10, 100]
                }
svm = SVC()
svm_gs = GridSearchCV(estimator = svm,
                      param_grid = svm_parameters)
svm_gs.fit(features_train, labels_train)

svm_winner = svm_gs.best_estimator_
svm_winner

svm_winner.score(features_validation, labels_validation)

0.7191011235955056

In [67]:
svm_winner

SVC(C=10, gamma=0.01)

# 13.6 Cross validation

In [68]:
svm_gs.cv_results_

{'mean_fit_time': array([0.03761535, 0.03879871, 0.04037232, 0.04104629, 0.03958716,
        0.03779006, 0.03856444, 0.03871102, 0.04087639, 0.04099998,
        0.03951249, 0.04217153, 0.04167399, 0.04228535, 0.0420866 ,
        0.04698787, 0.05128784, 0.05050983, 0.05206299, 0.04853926,
        0.07243791, 0.08089261, 0.0506803 , 0.05179377, 0.04931831]),
 'std_fit_time': array([0.00088025, 0.00117753, 0.00224078, 0.00105108, 0.00056697,
        0.00240032, 0.00092971, 0.00046068, 0.0012283 , 0.00104094,
        0.00079704, 0.00184638, 0.00069293, 0.00083706, 0.00061812,
        0.00231305, 0.00257062, 0.00359259, 0.00292135, 0.00148681,
        0.00989462, 0.00958061, 0.00168197, 0.00305677, 0.00183737]),
 'mean_score_time': array([0.03148098, 0.03251023, 0.03356123, 0.03412547, 0.03468294,
        0.0318368 , 0.03224893, 0.03247714, 0.032898  , 0.03261161,
        0.03088541, 0.03216619, 0.03216634, 0.03249645, 0.0331737 ,
        0.027706  , 0.02920213, 0.03147249, 0.03366189, 0.03374181,
        0.02636132, 0.02804232, 0.03070674, 0.03212404, 0.03256416]),
 'std_score_time': array([0.00052141, 0.000499  , 0.00034291, 0.00043611, 0.00159608,
        0.00069411, 0.00040449, 0.00062983, 0.00045143, 0.00065494,
        0.00160141, 0.00279217, 0.00101583, 0.00056079, 0.00036933,
        0.00064343, 0.0007589 , 0.00122927, 0.00095905, 0.00068356,
        0.00057146, 0.00113015, 0.00065672, 0.00056218, 0.00068398]),
 'param_C': masked_array(data=[0.01, 0.01, 0.01, 0.01, 0.01, 0.1, 0.1, 0.1, 0.1, 0.1,
                    1.0, 1.0, 1.0, 1.0, 1.0, 10.0, 10.0, 10.0, 10.0, 10.0,
                    100.0, 100.0, 100.0, 100.0, 100.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=1e+20),
 'param_gamma': masked_array(data=[0.01, 0.1, 1.0, 10.0, 100.0, 0.01, 0.1, 1.0, 10.0,
                    100.0, 0.01, 0.1, 1.0, 10.0, 100.0, 0.01, 0.1, 1.0,
                    10.0, 100.0, 0.01, 0.1, 1.0, 10.0, 100.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=1e+20),
 'param_kernel': masked_array(data=['rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf',
                    'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf',
                    'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf',
                    'rbf'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 0.01, 'gamma': 0.01, 'kernel': 'rbf'},
  {'C': 0.01, 'gamma': 0.1, 'kernel': 'rbf'},
  {'C': 0.01, 'gamma': 1, 'kernel': 'rbf'},
  {'C': 0.01, 'gamma': 10, 'kernel': 'rbf'},
  {'C': 0.01, 'gamma': 100, 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 1, 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 10, 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 100, 'kernel': 'rbf'},
  {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'},
  {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'},
  {'C': 1, 'gamma': 1, 'kernel': 'rbf'},
  {'C': 1, 'gamma': 10, 'kernel': 'rbf'},
  {'C': 1, 'gamma': 100, 'kernel': 'rbf'},
  {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'},
  {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'},
  {'C': 10, 'gamma': 1, 'kernel': 'rbf'},
  {'C': 10, 'gamma': 10, 'kernel': 'rbf'},
  {'C': 10, 'gamma': 100, 'kernel': 'rbf'},
  {'C': 100, 'gamma': 0.01, 'kernel': 'rbf'},
  {'C': 100, 'gamma': 0.1, 'kernel': 'rbf'},
  {'C': 100, 'gamma': 1, 'kernel': 'rbf'},
  {'C': 100, 'gamma': 10, 'kernel': 'rbf'},
  {'C': 100, 'gamma': 100, 'kernel': 'rbf'}],
 'split0_test_score': array([0.64485981, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.65420561, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.71962617, 0.73831776, 0.6728972 , 0.70093458, 0.70093458,
        0.82242991, 0.71962617, 0.6728972 , 0.70093458, 0.70093458,
        0.80373832, 0.74766355, 0.6635514 , 0.70093458, 0.70093458]),
 'split1_test_score': array([0.64485981, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.65420561, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.64485981, 0.71028037, 0.68224299, 0.6635514 , 0.6635514 ,
        0.73831776, 0.73831776, 0.6728972 , 0.65420561, 0.6635514 ,
        0.76635514, 0.74766355, 0.64485981, 0.65420561, 0.6635514 ]),
 'split2_test_score': array([0.64485981, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.6728972 , 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.71962617, 0.79439252, 0.73831776, 0.70093458, 0.71028037,
        0.81308411, 0.79439252, 0.75700935, 0.70093458, 0.71028037,
        0.82242991, 0.74766355, 0.73831776, 0.71028037, 0.71028037]),
 'split3_test_score': array([0.64485981, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.64485981, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.70093458, 0.77570093, 0.74766355, 0.70093458, 0.70093458,
        0.81308411, 0.75700935, 0.73831776, 0.70093458, 0.70093458,
        0.80373832, 0.74766355, 0.74766355, 0.70093458, 0.70093458]),
 'split4_test_score': array([0.6509434 , 0.6509434 , 0.6509434 , 0.6509434 , 0.6509434 ,
        0.66037736, 0.6509434 , 0.6509434 , 0.6509434 , 0.6509434 ,
        0.70754717, 0.80188679, 0.77358491, 0.69811321, 0.70754717,
        0.8490566 , 0.76415094, 0.77358491, 0.70754717, 0.69811321,
        0.82075472, 0.75471698, 0.77358491, 0.70754717, 0.69811321]),
 'mean_test_score': array([0.64607653, 0.64607653, 0.64607653, 0.64607653, 0.64607653,
        0.65730912, 0.64607653, 0.64607653, 0.64607653, 0.64607653,
        0.69851878, 0.76411568, 0.72294128, 0.69289367, 0.69664962,
        0.8071945 , 0.75469935, 0.72294128, 0.6929113 , 0.69476283,
        0.80340328, 0.74907424, 0.71359549, 0.69478046, 0.69476283]),
 'std_test_score': array([0.00243343, 0.00243343, 0.00243343, 0.00243343, 0.00243343,
        0.00923744, 0.00243343, 0.00243343, 0.00243343, 0.00243343,
        0.02777652, 0.03476014, 0.03891829, 0.01471177, 0.01695151,
        0.03687258, 0.0251742 , 0.04235721, 0.01952157, 0.0161391 ,
        0.02017857, 0.00282137, 0.05019872, 0.02061699, 0.0161391 ]),
 'rank_test_score': array([17, 17, 17, 17, 17, 16, 17, 17, 17, 17,  9,  3,  6, 15, 10,  1,  4,
         6, 14, 12,  2,  5,  8, 11, 12], dtype=int32)}

# Exercise 13.1

In [69]:
# IMPORTANT: ONLY RUN THIS CELL IF YOU HAVE CLONED THE REPO
test_data = pd.read_csv('test.csv')

In [ ]:
# IMPORTANT: ONLY RUN THIS CELL IF YOU ARE WORKING ON A COLAB
url = "https://raw.githubusercontent.com/luisguiserrano/manning/master/Chapter_13_End_to_end_example/test.csv"
test_data = pd.read_csv(url)

In [70]:
test_data.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [73]:
# Cleaning the data
test_data = test_data.drop('Cabin', axis=1)
test_data["Age"] = test_data["Age"].fillna(28.0)

# Catch! The test data has one missing fare. Let's fix that
average_fare = test_data["Fare"].mean()
test_data['Fare'] = test_data['Fare'].fillna(average_fare)

# Preprocessing the data
test_gender_columns = pd.get_dummies(test_data['Sex'], prefix='Sex')
test_embarked_columns = pandas.get_dummies(test_data["Embarked"], prefix="Embarked")
test_data = pandas.concat([test_data, test_gender_columns], axis=1)
test_data = pandas.concat([test_data, test_embarked_columns], axis=1)
test_data = test_data.drop(['Sex', 'Embarked'], axis=1)

# Another small catch, the test data has no missing 'Embarked' fields. Therefore, the processed test data will not
# have an 'Embarked_Q' column. We need to artificially add one filled with zeros.
test_data['Embarked_U'] = pandas.DataFrame([0 for i in range(len(test_data))])

test_categorized_pclass_columns = pandas.get_dummies(test_data['Pclass'], prefix='Pclass')
test_data = pandas.concat([test_data, test_categorized_pclass_columns], axis=1)
test_data = test_data.drop(['Pclass'], axis=1)

bins = [0, 10, 20, 30, 40, 50, 60, 70, 80]
test_categorized_age = pandas.cut(test_data['Age'], bins)
test_data['Categorized_age'] = categorized_age
test_data = test_data.drop(["Age"], axis=1)

test_cagegorized_age_columns = pandas.get_dummies(test_data['Categorized_age'], prefix='Categorized_age')
test_data = pandas.concat([test_data, test_cagegorized_age_columns], axis=1)
test_data = test_data.drop(['Categorized_age'], axis=1)

test_data = test_data.drop(['Name', 'Ticket', 'PassengerId'], axis=1)
test_data

KeyError: "['Cabin'] not found in axis"

Now, to check how many survivors were predicted by each model

In [74]:
# Logistic regression
sum(lr_model.predict(test_data))

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Age
- Embarked
- Name
- PassengerId
- Pclass
- ...
Feature names seen at fit time, yet now missing:
- Categorized_age_(0, 10]
- Categorized_age_(10, 20]
- Categorized_age_(20, 30]
- Categorized_age_(30, 40]
- Categorized_age_(40, 50]
- ...

In [ ]:
# Decision tree
sum(dt_model.predict(test_data))

In [ ]:
# Naive Bayes
sum(nb_model.predict(test_data))

In [ ]:
# Support vector machine
sum(svm_model.predict(test_data))

In [ ]:
# Random forest
sum(rf_model.predict(test_data))

In [75]:
# Gradient boosting
sum(gb_model.predict(test_data))

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Age
- Embarked
- Name
- PassengerId
- Pclass
- ...
Feature names seen at fit time, yet now missing:
- Categorized_age_(0, 10]
- Categorized_age_(10, 20]
- Categorized_age_(20, 30]
- Categorized_age_(30, 40]
- Categorized_age_(40, 50]
- ...

In [ ]:
# AdaBoost
sum(ab_model.predict(test_data))

Since the three strongest models in terms of accuracy were random forests, gradient boosting, and adaboost, and they predicted that 154, 156, and 155 passengers survived out of the 418 in the test set, a good estimate for the number of survivors is the average of these three predictions, or 155.